folders:
  current: C:\Users\larue\OneDrive - Chapman University\Research\Methanol Decomposition\2022-Current Pt(111)\Sum Frequency Generation (SFG) Spectroscopy\Data Analysis
  data: C:\Users\larue\Chapman University\LaRue CatLab - Data
  figures: figures
  fits: fits
